/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.picklejar;

import java.util.logging.Logger;

public class Library {
  public boolean someLibraryMethod() {
    Logger logger = Logger.getLogger(Library.class.getName());
    logger.info("someLibraryMethod called");
    return true;
  }
}
