/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.picklejar;

import org.picklejar.session.Session;
import java.util.logging.Logger;
import java.net.*;
import java.io.*;

public class Picklejar {
  public static String host;
  public static Integer port;
  private static final Logger logger = Logger.getLogger(Picklejar.class.getName());

  public Picklejar(String host, Integer port) {
    Picklejar.host = host;
    Picklejar.port = port;
  }

  public static void main(String[] args) {
    Picklejar picklejar = new Picklejar("127.0.0.0", 8080);
    picklejar.Start();
  }

  public void Start() {
    logger.info("Starting Picklejar on " + this.host + ":" + this.port);
    try {
      ServerSocket server = new ServerSocket(port);
      while (true) {
        Socket client = server.accept();
        logger.info("Connection from " + client.getInetAddress());
        // client.close();
        Session session = new Session();
        session.startSession(client);
      }
    } catch (IOException e) {
      logger.severe(e.getMessage());
    }
  }

  public void Stop() {
    logger.info("Stopping Picklejar on " + this.host + ":" + this.port);
    try {
      ServerSocket server = new ServerSocket(port);
      server.close();
    } catch (IOException e) {
      logger.severe(e.getMessage());
    }

  }
}
